In [1]:

from sklearn import svm

train_data = [[0, 0, 0, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1], [0, 3, 0, 0, 0, 1, 0, 0], [0, 11, 0, 0, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 4]]
test_data = [[0, 0, 0, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 1, 0, 0]]


clf = svm.OneClassSVM(nu=0.1, kernel="rbf", gamma=0.1)
clf.fit(train_data)

pred_test = clf.predict(test_data)
pred_test

array([-1.,  1.])

In [4]:

num_string = '001101010111'
[int(i) for i in num_string]

[0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1]

In [5]:

import pandas as pd

pd.read_html('./Hans Rosling Examples/data/html/gini_per_country.html')[0]

,Country,UN_Richest_per_Poorest_10_Percent,UN_Richest_per_Poorest_20_Percent,World_Bank_Gini_Percent,World_Bank_Gini_Year,CIA_Richest_per_Poorest_10_Percent,CIA_Richest_per_Poorest_Year,CIA_Gini_Percent,CIA_Gini_Year
0,Afghanistan,NaN,NaN,27.8,2008.0,NaN,NaN,NaN,NaN
1,Albania,7.2,4.8,29.0,2012.0,7.2,2004,26.9,2012
2,Algeria,9.6,6.1,35.3,1995.0,9.6,1995,35.3,1995
3,Angola,NaN,NaN,42.7,2008.0,NaN,NaN,NaN,NaN
4,Argentina,31.6,17.8,42.7,2014.0,35.0,2007 Jan.-Mar.,45.8,2009
5,Armenia,8.0,5.0,31.5,2014.0,25.8,2004,30.3,2012
6,Australia,12.5,7.0,34.9,2010.0,12.7,1994,30.3,2008
7,Austria,6.9,4.4,30.5,2012.0,6.8,2004,26.3,2007
8,Azerbaijan,9.7,6.0,33.7,2008.0,9.5,2001,33.7,2008
9,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Bangladesh,7.5,4.9,32.0,2010.0,7.5,2000,32.1,2010
11,Belarus,6.9,4.5,26.0,2012.0,6.9,2002,26.5,2011
12,Belgium,8.2,4.9,27.6,2012.0,8.3,2000,25.9,2013
13,Belize,NaN,NaN,53.3,1999.0,NaN,NaN,NaN,NaN
14,Benin,9.4,6.0,43.5,2012.0,9.4,2003,36.5,2003
15,Bhutan,NaN,NaN,38.7,2012.0,NaN,NaN,38.7,2012
16,Bolivia,93.9,42.3,48.4,2014.0,157.3,2002,46.6,2012
17,Bosnia and Herzegovina,5.4,3.8,33.0,2007.0,5.5,2001,36.2,2007
18,Botswana,43.0,20.4,60.5,2009.0,NaN,NaN,63.0,1993
19,Brazil,16.0,13.0,48.4,2014.0,14.6,2013,48.7,2013
20,Bulgaria,7.0,4.4,36.0,2012.0,8.8,2005,35.4,2012
21,Burkina Faso,11.6,6.9,39.8,2009.0,11.5,2003,39.5,2007
22,Burundi,19.3,9.5,33.4,2006.0,19.3,1998,42.4,1998
23,Cambodia,12.2,7.3,30.8,2012.0,12.0,2004,37.9,2008
24,Cameroon,15.7,9.1,42.8,2007.0,15.4,2001,44.6,2001
25,Canada,9.4,5.5,33.7,2010.0,9.5,2000,32.1,2005
26,Cape Verde,NaN,NaN,42.7,2007.0,NaN,NaN,NaN,NaN
27,Central African Republic,69.2,32.7,56.2,2008.0,68.1,1993,61.3,1993
28,Chad,NaN,NaN,43.3,2011.0,NaN,NaN,43.3,2011
29,Chile,26.2,15.7,50.5,2013.0,32.1,2003,52.1,2009
...,...,...,...,...,...,...,...,...,...
146,Sudan,NaN,NaN,35.4,2009.0,NaN,NaN,NaN,NaN
147,Suriname,NaN,NaN,57.6,1999.0,NaN,NaN,NaN,NaN
148,Swaziland,25.1,13.0,51.5,2010.0,25.4,2001,50.4,2001
149,Sweden,6.2,4.0,27.3,2012.0,6.2,2000,24.9,2013
150,Switzerland,9.0,5.5,31.6,2012.0,8.9,2000,28.7,2012
151,Syria,NaN,NaN,35.8,2004.0,NaN,NaN,NaN,NaN
152,Taiwan,NaN,NaN,NaN,NaN,6.1,2002,33.8,2012
153,Tajikistan,7.8,5.2,30.8,2009.0,7.8,2003,32.6,2006
154,Tanzania,9.2,5.8,37.8,2011.0,9.3,2000,37.6,2007
155,Thailand,12.6,7.7,39.3,2012.0,12.4,2002,39.4,2010
156,Timor-Leste,NaN,NaN,31.6,2007.0,NaN,NaN,31.9,2007
157,Togo,NaN,NaN,46.0,2011.0,NaN,NaN,NaN,NaN
158,Trinidad and Tobago,12.9,7.6,40.3,1992.0,NaN,NaN,NaN,NaN
159,Tunisia,13.4,7.9,35.8,2010.0,13.7,2000,40.0,2005
160,Turkey,6.6,4.6,40.2,2012.0,17.1,2003,40.2,2010
161,Turkmenistan,12.3,7.7,40.8,1998.0,12.2,1998,40.8,1998
162,Uganda,16.6,9.2,42.4,2012.0,16.4,2002,39.5,2013
163,Ukraine,5.9,4.1,24.6,2013.0,7.6,2006,28.2,2009
164,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,United Kingdom,13.8,7.2,32.6,2012.0,13.6,1999,32.4,2012
166,United States,18.5,9.4,46.1,2013.0,14.0,2014,47.0,2014
167,Uruguay,11.8,NaN,41.6,2014.0,17.9,2003,45.3,2010
168,Uzbekistan,10.6,6.2,36.7,2003.0,10.6,2003,36.8,2003
169,Venezuela,18.8,16.0,46.9,2006.0,50.3,2003,39.0,2011
170,Vietnam,6.9,4.9,38.9,2012.0,10.0,2004,37.6,2008
171,Palestine,NaN,NaN,35.5,2009.0,NaN,NaN,NaN,NaN
172,Yemen,8.6,5.6,37.7,2005.0,8.6,2003,37.7,2005
173,Zambia,NaN,NaN,55.6,2010.0,NaN,NaN,57.5,2010
174,Zimbabwe,NaN,NaN,50.1,1995.0,NaN,NaN,50.1,2006
175,World,NaN,NaN,NaN,NaN,12.0,2002,38.0,2007

In [2]:
# %load load_magic/lists.py

from difflib import SequenceMatcher
import time

def similar(a, b):
    return SequenceMatcher(None, str(a), str(b)).ratio()

def check_4_doubles(item_list):
    rows_list = []
    n = len(item_list)
    t0 = time.time()
    for i in range(n-1):
        first_item = item_list[i]
        max_similarity = 0.0
        max_item = first_item
        for j in range(i+1, n):
            second_item = item_list[j]

            # Assume the first item is never identical to the second item
            this_similarity = similar(str(first_item), str(second_item))
            
            if this_similarity > max_similarity:
                max_similarity = this_similarity
                max_item = second_item

        # Get input row in dictionary format; key = col_name
        row_dict = {}
        row_dict['first_item'] = first_item
        row_dict['second_item'] = max_item
        row_dict['first_bytes'] = '-'.join(str(x) for x in bytearray(str(first_item),
                                                                     encoding=encoding, errors='replace'))
        row_dict['second_bytes'] = '-'.join(str(x) for x in bytearray(str(max_item),
                                                                      encoding=encoding, errors='replace'))
        row_dict['max_similarity'] = max_similarity

        rows_list.append(row_dict)
    t1 = time.time()
    print(t1-t0, time.ctime(t1))

    column_list = ['first_item', 'second_item', 'first_bytes', 'second_bytes', 'max_similarity']
    item_similarities_df = pd.DataFrame(rows_list, columns=column_list)

    return item_similarities_df

#Check the closest names for typos
def check_for_typos(left_list, right_list):
    rows_list = []
    for left_item in left_list:
        max_similarity = 0.0
        max_item = left_item
        for right_item in right_list:
            this_similarity = similar(left_item, right_item)
            if this_similarity > max_similarity:
                max_similarity = this_similarity
                max_item = right_item

        # Get input row in dictionary format; key = col_name
        row_dict = {}
        row_dict['left_item'] = left_item
        row_dict['right_item'] = max_item
        row_dict['max_similarity'] = max_similarity

        rows_list.append(row_dict)

    column_list = ['left_item', 'right_item', 'max_similarity']
    name_similarities_df = pd.DataFrame(rows_list, columns=column_list)
    
    return name_similarities_df